In [1]:
import numpy as np
import time

In [2]:

start=time.time()
a=[[0,1,2],[3,4,5]]
print(type(a))
a
b=np.array(a)    #2d array
stop=time.time() 
print(stop-start) #time taken to convert list to 2d array

<class 'list'>
0.0


In [3]:
 
print(type(b))
print(b)
print("The dimension of the matrix is ",b.ndim)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
The dimension of the matrix is  2


In [4]:
"""start=time.time()"""


In [5]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
u=np.asmatrix(x)
v=np.asmatrix(y)
print(u,v)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
u+v #sum of 2 matrices

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [8]:
print(u,v)
u*v #product of 2 matrices

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
np.linspace(1,10,3) # 3 equi spaced numbers bw 1 and 10 

array([ 1. ,  5.5, 10. ])

In [10]:
ar=np.array(range(1,100)) #odd numbers bw 1 to 100
lst=[]
for i in ar:
    if(i%2!=0):
        lst.append(i)
print(np.array(lst))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [11]:
a1=[[11,12,13,14,15],[16,17,18,19,20]]
b=np.array(a1)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
b.reshape(5,2) #reshaping using reshape method

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [13]:
"""stop=time.time()
print(stop-start)"""

10.825043439865112
